In [2]:
import numpy as np
import pandas  as pd

def sep ():
    print('*' * 20)

# Creating Dataframe

In [3]:
df = pd.DataFrame([[1,2,3],[1,2,4],[4,5,6],[6,7,8]]
                  
                  , columns=['A' , 'b' ,'c']
                  , index=['A','b','c','d']
                  )
print(df)
sep()
print(df.head(1))
sep()
print(df.tail(2))

   A  b  c
A  1  2  3
b  1  2  4
c  4  5  6
d  6  7  8
********************
   A  b  c
A  1  2  3
********************
   A  b  c
c  4  5  6
d  6  7  8

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to d
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   b       4 non-null      int64
 2   c       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes
None

### Get Describtion And Data Exploration

In [5]:
df.describe().T

   count  mean       std  min   25%  50%  75%  max
A    4.0  3.00  2.449490  1.0  1.00  2.5  4.5  6.0
b    4.0  4.00  2.449490  2.0  2.00  3.5  5.5  7.0
c    4.0  5.25  2.217356  3.0  3.75  5.0  6.5  8.0

In [6]:
print(df.nunique()) #the num of unique values in each column

A    3
b    3
c    4
dtype: int64

In [7]:
print(df)
print(df['A'].nunique())

   A  b  c
A  1  2  3
b  1  2  4
c  4  5  6
d  6  7  8
3

# Loading Dataset

In [8]:
car = pd.read_csv("/Users/khaledayman/Desktop/main/workspace/lessonsVs/Newfile.csv")
print(car.head())

   symboling  normalized-losses         make fuel-type aspiration  \
0          3                NaN  alfa-romero       gas        std
1          1                NaN  alfa-romero       gas        std
2          2              164.0         audi       gas        std
3          2              164.0         audi       gas        std
4          2                NaN         audi       gas        std

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...
1          two    hatchback          rwd           front        94.5  ...
2         four        sedan          fwd           front        99.8  ...
3         four        sedan          4wd           front        99.4  ...
4          two        sedan          fwd           front        99.8  ...

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0          130         mpfi  3.47    2.68               9.0      111.0
1          152         mpfi  2.68    3.47               9.0      154.0
2          109         mpfi  3.19    3.40              10.0      102.0
3          136         mpfi  3.19    3.40               8.0      115.0
4          136         mpfi  3.19    3.40               8.5      110.0

   peak-rpm city-mpg  highway-mpg  price
0    5000.0       21           27  16500
1    5000.0       19           26  16500
2    5500.0       24           30  13950
3    5500.0       18           22  17450
4    5500.0       19           25  15250

[5 rows x 26 columns]

In [9]:
print(car.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          200 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               200 non-null    object
 3   fuel-type          200 non-null    object
 4   aspiration         200 non-null    object
 5   num-of-doors       198 non-null    object
 6   body-style         200 non-null    object
 7   drive-wheels       200 non-null    object
 8   engine-location    200 non-null    object
 9   wheel-base         200 non-null    float64
 10  length             200 non-null    float64
 11  width              200 non-null    float64
 12  height             200 non-null    float64
 13  curb-weight        200 non-null    int64
 14  engine-type        200 non-null    object
 15  num-of-cylinders   200 non-null    object
 16  engine-size        200 non-null    int64
 17  fuel-system        200 non-null    object
 18  bore               196 non-null    float64
 19  stroke             196 non-null    float64
 20  compression-ratio  200 non-null    float64
 21  horsepower         198 non-null    float64
 22  peak-rpm           198 non-null    float64
 23  city-mpg           200 non-null    int64
 24  highway-mpg        200 non-null    int64
 25  price              200 non-null    int64
dtypes: float64(10), int64(6), object(10)
memory usage: 40.8+ KB
None

In [10]:
print(car.describe())

        symboling  normalized-losses  wheel-base      length       width  \
count  200.000000         164.000000  200.000000  200.000000  200.000000
mean     0.830000         122.000000   98.848000  174.228000   65.898000
std      1.248557          35.442168    6.038261   12.347132    2.102904
min     -2.000000          65.000000   86.600000  141.100000   60.300000
25%      0.000000          94.000000   94.500000  166.675000   64.175000
50%      1.000000         115.000000   97.000000  173.200000   65.500000
75%      2.000000         150.000000  102.400000  183.500000   66.675000
max      3.000000         256.000000  120.900000  208.100000   72.000000

           height  curb-weight  engine-size        bore      stroke  \
count  200.000000   200.000000   200.000000  196.000000  196.000000
mean    53.791500  2555.705000   126.860000    3.330000    3.259847
std      2.428449   518.594552    41.650501    0.271303    0.317383
min     47.800000  1488.000000    61.000000    2.540000    2.070000
25%     52.000000  2163.000000    97.750000    3.150000    3.110000
50%     54.100000  2414.000000   119.500000    3.310000    3.290000
75%     55.525000  2928.250000   142.000000    3.590000    3.410000
max     59.800000  4066.000000   326.000000    3.940000    4.170000

       compression-ratio  horsepower     peak-rpm    city-mpg  highway-mpg  \
count         200.000000  198.000000   198.000000  200.000000   200.000000
mean           10.170100  103.358586  5118.181818   25.200000    30.705000
std             4.014163   37.645120   481.666657    6.432487     6.827227
min             7.000000   48.000000  4150.000000   13.000000    16.000000
25%             8.575000   70.000000  4800.000000   19.000000    25.000000
50%             9.000000   95.000000  5200.000000   24.000000    30.000000
75%             9.400000  116.000000  5500.000000   30.000000    34.000000
max            23.000000  262.000000  6600.000000   49.000000    54.000000

              price
count    200.000000
mean   13205.690000
std     7966.982558
min     5118.000000
25%     7775.000000
50%    10270.000000
75%    16500.750000
max    45400.000000

In [11]:
print(car.nunique())

symboling              6
normalized-losses     51
make                  22
fuel-type              2
aspiration             2
num-of-doors           2
body-style             5
drive-wheels           3
engine-location        2
wheel-base            52
length                73
width                 43
height                49
curb-weight          169
engine-type            6
num-of-cylinders       7
engine-size           43
fuel-system            8
bore                  38
stroke                36
compression-ratio     32
horsepower            58
peak-rpm              22
city-mpg              29
highway-mpg           30
price                185
dtype: int64

In [12]:
print(car['symboling'].unique())
print(car['symboling'].nunique())

[ 3  1  2  0 -1 -2]
6

In [13]:
coffee = pd . read_excel('/Users/khaledayman/Desktop/main/workspace/Google/DataSets/coffeeOrdersData.xlsx')
print(coffee)

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [ ]:
print(car.tail())

     symboling  normalized-losses   make fuel-type aspiration num-of-doors  \
195         -1               95.0  volvo       gas        std         four
196         -1               95.0  volvo       gas      turbo         four
197         -1               95.0  volvo       gas        std         four
198         -1               95.0  volvo    diesel      turbo         four
199         -1               95.0  volvo       gas      turbo         four

    body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
195      sedan          rwd           front       109.1  ...          141
196      sedan          rwd           front       109.1  ...          141
197      sedan          rwd           front       109.1  ...          173
198      sedan          rwd           front       109.1  ...          145
199      sedan          rwd           front       109.1  ...          141

     fuel-system  bore  stroke compression-ratio horsepower  peak-rpm  \
195         mpfi  3.78    3.15               9.5      114.0    5400.0
196         mpfi  3.78    3.15               8.7      160.0    5300.0
197         mpfi  3.58    2.87               8.8      134.0    5500.0
198          idi  3.01    3.40              23.0      106.0    4800.0
199         mpfi  3.78    3.15               9.5      114.0    5400.0

    city-mpg  highway-mpg  price
195       23           28  16845
196       19           25  19045
197       18           23  21485
198       26           27  22470
199       19           25  22625

[5 rows x 26 columns]

In [ ]:
display(car)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625

In [ ]:
print(car.loc[4])

symboling                 2
normalized-losses       NaN
make                   audi
fuel-type               gas
aspiration              std
num-of-doors            two
body-style            sedan
drive-wheels            fwd
engine-location       front
wheel-base             99.8
length                177.3
width                  66.3
height                 53.1
curb-weight            2507
engine-type             ohc
num-of-cylinders       five
engine-size             136
fuel-system            mpfi
bore                   3.19
stroke                  3.4
compression-ratio       8.5
horsepower            110.0
peak-rpm             5500.0
city-mpg                 19
highway-mpg              25
price                 15250
Name: 4, dtype: object

In [ ]:
print(car.loc[[4,1,6]])

   symboling  normalized-losses         make fuel-type aspiration  \
4          2                NaN         audi       gas        std
1          1                NaN  alfa-romero       gas        std
6          1                NaN         audi       gas        std

  num-of-doors body-style drive-wheels engine-location  wheel-base  ...  \
4          two      sedan          fwd           front        99.8  ...
1          two  hatchback          rwd           front        94.5  ...
6         four      wagon          fwd           front       105.8  ...

   engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
4          136         mpfi  3.19    3.40               8.5      110.0
1          152         mpfi  2.68    3.47               9.0      154.0
6          136         mpfi  3.19    3.40               8.5      110.0

   peak-rpm city-mpg  highway-mpg  price
4    5500.0       19           25  15250
1    5000.0       19           26  16500
6    5500.0       19           25  18920

[3 rows x 26 columns]

In [ ]:
print(car.loc[20:30])

    symboling  normalized-losses   make fuel-type aspiration num-of-doors  \
20          1              118.0  dodge       gas        std          two
21          1              118.0  dodge       gas      turbo          two
22          1              148.0  dodge       gas        std         four
23          1              148.0  dodge       gas        std         four
24          1              148.0  dodge       gas        std         four
25          1              148.0  dodge       gas      turbo          NaN
26         -1              110.0  dodge       gas        std         four
27          3              145.0  dodge       gas      turbo          two
28          2              137.0  honda       gas        std          two
29          2              137.0  honda       gas        std          two
30          1              101.0  honda       gas        std          two

   body-style drive-wheels engine-location  wheel-base  ...  engine-size  \
20  hatchback          fwd           front        93.7  ...           90
21  hatchback          fwd           front        93.7  ...           98
22  hatchback          fwd           front        93.7  ...           90
23      sedan          fwd           front        93.7  ...           90
24      sedan          fwd           front        93.7  ...           90
25      sedan          fwd           front        93.7  ...           98
26      wagon          fwd           front       103.3  ...          122
27  hatchback          fwd           front        95.9  ...          156
28  hatchback          fwd           front        86.6  ...           92
29  hatchback          fwd           front        86.6  ...           92
30  hatchback          fwd           front        93.7  ...           79

    fuel-system  bore  stroke compression-ratio horsepower  peak-rpm city-mpg  \
20         2bbl  2.97    3.23               9.4       68.0    5500.0       31
21         mpfi  3.03    3.39               7.6      102.0    5500.0       24
22         2bbl  2.97    3.23               9.4       68.0    5500.0       31
23         2bbl  2.97    3.23               9.4       68.0    5500.0       31
24         2bbl  2.97    3.23               9.4       68.0    5500.0       31
25         mpfi  3.03    3.39               7.6      102.0    5500.0       24
26         2bbl  3.34    3.46               8.5       88.0    5000.0       24
27          mfi  3.60    3.90               7.0      145.0    5000.0       19
28         1bbl  2.91    3.41               9.6       58.0    4800.0       49
29         1bbl  2.91    3.41               9.2       76.0    6000.0       31
30         1bbl  2.91    3.07              10.1       60.0    5500.0       38

    highway-mpg  price
20           38   6377
21           30   7957
22           38   6229
23           38   6692
24           38   7609
25           30   8558
26           30   8921
27           24  12964
28           54   6479
29           38   6855
30           42   5399

[11 rows x 26 columns]

In [ ]:
print(car.loc[20:30 , ['symboling', 'normalized-losses',   'make', 'fuel-type', 'aspiration', 'num-of-doors']])

    symboling  normalized-losses   make fuel-type aspiration num-of-doors
20          1              118.0  dodge       gas        std          two
21          1              118.0  dodge       gas      turbo          two
22          1              148.0  dodge       gas        std         four
23          1              148.0  dodge       gas        std         four
24          1              148.0  dodge       gas        std         four
25          1              148.0  dodge       gas      turbo          NaN
26         -1              110.0  dodge       gas        std         four
27          3              145.0  dodge       gas      turbo          two
28          2              137.0  honda       gas        std          two
29          2              137.0  honda       gas        std          two
30          1              101.0  honda       gas        std          two

In [ ]:
print(car.loc[20:30 , ['normalized-losses', 'fuel-type', 'num-of-doors']])

    normalized-losses fuel-type num-of-doors
20              118.0       gas          two
21              118.0       gas          two
22              148.0       gas         four
23              148.0       gas         four
24              148.0       gas         four
25              148.0       gas          NaN
26              110.0       gas         four
27              145.0       gas          two
28              137.0       gas          two
29              137.0       gas          two
30              101.0       gas          two

In [ ]:
print(car.loc[: , ['symboling', 'aspiration', 'num-of-doors']])
print(car.loc)

     symboling aspiration num-of-doors
0            3        std          two
1            1        std          two
2            2        std         four
3            2        std         four
4            2        std          two
..         ...        ...          ...
195         -1        std         four
196         -1      turbo         four
197         -1        std         four
198         -1      turbo         four
199         -1      turbo         four

[200 rows x 3 columns]
<pandas.core.indexing._LocIndexer object at 0x14f34bfc0>

 loc      >> get the rows by (index / slicing / specification ) >> [ row ] 
 / [ [ multible rows ] ] /  [range 10:30] [range 10:30 , ["specefication column 1" ,"specifecation column 2"..... ]]


 iloc      >> get the rows by (index / slicing / specification ) >> [ row ] 
 / [ [ multible rows ] ] /  [range 10:30] [range 10:30 , ["specefication column 1" ,"specifecation column 2"..... ]]

In [ ]:
# print(car.iloc[: , [0,2,3]]) #..> Iloc by specify column by indexing
print(car.iloc[[1,2,3], [0,2,3]]) #..> Iloc by specify column by indexing

   symboling         make fuel-type
1          1  alfa-romero       gas
2          2         audi       gas
3          2         audi       gas

In [ ]:
print(car.at[10,'num-of-doors'])

two

In [ ]:
print(car.iat[10,2])

bmw

In [ ]:
# print(car.symboling) #one word >> get the all column
# print(car.num-of-doors) #  multuble word >> error
print(car['num-of-doors']) 
print(car.loc[1:29, 'num-of-doors'])

0       two
1       two
2      four
3      four
4       two
       ...
195    four
196    four
197    four
198    four
199    four
Name: num-of-doors, Length: 200, dtype: object
1      two
2     four
3     four
4      two
5     four
6     four
7     four
8      two
9     four
10     two
11    four
12    four
13    four
14     two
15    four
16     two
17     two
18    four
19     two
20     two
21     two
22    four
23    four
24    four
25     NaN
26    four
27     two
28     two
29     two
Name: num-of-doors, dtype: object

In [ ]:
print (car.sort_values("symboling" , ascending= True))

     symboling  normalized-losses           make fuel-type aspiration  \
193         -2              103.0          volvo       gas      turbo
191         -2              103.0          volvo       gas        std
189         -2              103.0          volvo       gas        std
199         -1               95.0          volvo       gas      turbo
66          -1               93.0  mercedes-benz    diesel      turbo
..         ...                ...            ...       ...        ...
127          3              150.0           saab       gas        std
129          3              150.0           saab       gas        std
131          3              150.0           saab       gas      turbo
100          3              194.0         nissan       gas        std
0            3                NaN    alfa-romero       gas        std

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
193         four        sedan          rwd           front       104.3  ...
191         four        sedan          rwd           front       104.3  ...
189         four        sedan          rwd           front       104.3  ...
199         four        sedan          rwd           front       109.1  ...
66          four        sedan          rwd           front       115.6  ...
..           ...          ...          ...             ...         ...  ...
127          two    hatchback          fwd           front        99.1  ...
129          two    hatchback          fwd           front        99.1  ...
131          two    hatchback          fwd           front        99.1  ...
100          two    hatchback          rwd           front        91.3  ...
0            two  convertible          rwd           front        88.6  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
193          130         mpfi  3.62    3.15              7.50      162.0
191          141         mpfi  3.78    3.15              9.50      114.0
189          141         mpfi  3.78    3.15              9.50      114.0
199          141         mpfi  3.78    3.15              9.50      114.0
66           183          idi  3.58    3.64             21.50      123.0
..           ...          ...   ...     ...               ...        ...
127          121         mpfi  3.54    3.07              9.31      110.0
129          121         mpfi  2.54    2.07              9.30      110.0
131          121         mpfi  3.54    3.07              9.00      160.0
100          181         mpfi  3.43    3.27              9.00      160.0
0            130         mpfi  3.47    2.68              9.00      111.0

     peak-rpm city-mpg  highway-mpg  price
193    5100.0       17           22  18420
191    5400.0       24           28  15985
189    5400.0       23           28  12940
199    5400.0       19           25  22625
66     4350.0       22           25  31600
..        ...      ...          ...    ...
127    5250.0       21           28  11850
129    5250.0       21           28  15040
131    5500.0       19           26  18150
100    5200.0       19           25  17199
0      5000.0       21           27  16500

[200 rows x 26 columns]

In [15]:
car.sort_values(["symboling","normalized-losses" ] , ascending= [1,0])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
189,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,12940
191,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,24,28,15985
193,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100.0,17,22,18420
84,-1,137.0,mitsubishi,gas,std,four,sedan,fwd,front,96.3,...,110,spdi,3.17,3.46,7.5,116.0,5500.0,23,30,9279
26,-1,110.0,dodge,gas,std,four,wagon,fwd,front,103.3,...,122,2bbl,3.34,3.46,8.5,88.0,5000.0,24,30,8921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,3,NaN,plymouth,gas,turbo,two,hatchback,rwd,front,95.9,...,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,12764
122,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,32528
123,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,34028
124,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,37028
184,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90.0,5500.0,24,29,11595

In [ ]:
# print(car.loc[car["num-of-doors"] == 'two'])
print(car.loc[(car["fuel-type"] == 'gas')|(car["fuel-type"] == 'diesel')])
print(car.loc[(car["fuel-type"] == 'gas')|(car["fuel-type"] == 'diesel'), ['symboling']])

     symboling  normalized-losses         make fuel-type aspiration  \
0            3                NaN  alfa-romero       gas        std
1            1                NaN  alfa-romero       gas        std
2            2              164.0         audi       gas        std
3            2              164.0         audi       gas        std
4            2                NaN         audi       gas        std
..         ...                ...          ...       ...        ...
195         -1               95.0        volvo       gas        std
196         -1               95.0        volvo       gas      turbo
197         -1               95.0        volvo       gas        std
198         -1               95.0        volvo    diesel      turbo
199         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two    hatchback          rwd           front        94.5  ...
2           four        sedan          fwd           front        99.8  ...
3           four        sedan          4wd           front        99.4  ...
4            two        sedan          fwd           front        99.8  ...
..           ...          ...          ...             ...         ...  ...
195         four        sedan          rwd           front       109.1  ...
196         four        sedan          rwd           front       109.1  ...
197         four        sedan          rwd           front       109.1  ...
198         four        sedan          rwd           front       109.1  ...
199         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0      111.0
1            152         mpfi  2.68    3.47               9.0      154.0
2            109         mpfi  3.19    3.40              10.0      102.0
3            136         mpfi  3.19    3.40               8.0      115.0
4            136         mpfi  3.19    3.40               8.5      110.0
..           ...          ...   ...     ...               ...        ...
195          141         mpfi  3.78    3.15               9.5      114.0
196          141         mpfi  3.78    3.15               8.7      160.0
197          173         mpfi  3.58    2.87               8.8      134.0
198          145          idi  3.01    3.40              23.0      106.0
199          141         mpfi  3.78    3.15               9.5      114.0

     peak-rpm city-mpg  highway-mpg  price
0      5000.0       21           27  16500
1      5000.0       19           26  16500
2      5500.0       24           30  13950
3      5500.0       18           22  17450
4      5500.0       19           25  15250
..        ...      ...          ...    ...
195    5400.0       23           28  16845
196    5300.0       19           25  19045
197    5500.0       18           23  21485
198    4800.0       26           27  22470
199    5400.0       19           25  22625

[200 rows x 26 columns]
     symboling
0            3
1            1
2            2
3            2
4            2
..         ...
195         -1
196         -1
197         -1
198         -1
199         -1

[200 rows x 1 columns]

In [ ]:
display(car.head())

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250

In [ ]:
display(car.loc[car['engine-size' ] > 150 , ['make']])

              make
1      alfa-romero
10             bmw
11             bmw
12             bmw
13             bmw
14             bmw
15             bmw
27           dodge
43          jaguar
44          jaguar
45          jaguar
63   mercedes-benz
64   mercedes-benz
65   mercedes-benz
66   mercedes-benz
67   mercedes-benz
68   mercedes-benz
69   mercedes-benz
70   mercedes-benz
78      mitsubishi
79      mitsubishi
80      mitsubishi
97          nissan
98          nissan
99          nissan
100         nissan
101         nissan
102         nissan
104         peugot
106         peugot
108         peugot
110         peugot
112         peugot
120       plymouth
121        porsche
122        porsche
123        porsche
124        porsche
173         toyota
174         toyota
175         toyota
176         toyota
197          volvo

In [ ]:
display(car[car['engine-location'] .str.contains('front')])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625

In [ ]:
display( car.loc[car['make'] .str.contains('peugot') , ['make', 'price']] )

       make  price
103  peugot  11900
104  peugot  13200
105  peugot  12440
106  peugot  13860
107  peugot  15580
108  peugot  16900
109  peugot  16695
110  peugot  17075
111  peugot  16630
112  peugot  17950
113  peugot  18150

In [ ]:
display( car.loc[car['make'] .str.contains('peugot|toyota') , ['make', 'price']] )

       make  price
103  peugot  11900
104  peugot  13200
105  peugot  12440
106  peugot  13860
107  peugot  15580
108  peugot  16900
109  peugot  16695
110  peugot  17075
111  peugot  16630
112  peugot  17950
113  peugot  18150
145  toyota   5348
146  toyota   6338
147  toyota   6488
148  toyota   6918
149  toyota   7898
150  toyota   8778
151  toyota   6938
152  toyota   7198
153  toyota   7898
154  toyota   7788
155  toyota   7738
156  toyota   8358
157  toyota   9258
158  toyota   8058
159  toyota   8238
160  toyota   9298
161  toyota   9538
162  toyota   8449
163  toyota   9639
164  toyota   9989
165  toyota  11199
166  toyota  11549
167  toyota  17669
168  toyota   8948
169  toyota  10698
170  toyota   9988
171  toyota  10898
172  toyota  11248
173  toyota  16558
174  toyota  15998
175  toyota  15690
176  toyota  15750

In [ ]:
display (car [car['make'].isin(['toyota'])])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
145,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,35,39,5348
146,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6338
147,1,74.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6488
148,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918
149,0,81.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,27,32,7898
150,0,91.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,27,32,8778
151,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,6938
152,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,7198
153,0,91.0,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56.0,4500.0,34,36,7898
154,0,91.0,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56.0,4500.0,38,47,7788
155,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,38,47,7738
156,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,8358
157,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,9258
158,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8058
159,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8238
160,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9298
161,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9538
162,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,8449
163,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,9639
164,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,9989
165,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11199
166,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11549
167,2,134.0,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,17669
168,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,29,34,8948
169,-1,65.0,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.5,73.0,4500.0,30,33,10698
170,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,9988
171,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,10898
172,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,11248
173,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200.0,20,24,16558
174,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200.0,19,24,15998
175,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.2,156.0,5200.0,20,24,15690
176,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750

In [16]:
display(car[
    car['make'].isin(
        ['toyota','peugot']
    ) 
    & (car['price'] > 11111)] 
    )

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
103,0,161.0,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97.0,5000.0,19,24,11900
104,0,161.0,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95.0,4150.0,28,33,13200
105,0,NaN,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97.0,5000.0,19,24,12440
106,0,NaN,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95.0,4150.0,25,25,13860
107,0,161.0,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,2.19,8.4,95.0,5000.0,19,24,15580
108,0,161.0,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95.0,4150.0,28,33,16900
109,0,NaN,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,2.19,8.4,95.0,5000.0,19,24,16695
110,0,NaN,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95.0,4150.0,25,25,17075
111,0,161.0,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97.0,5000.0,19,24,16630
112,0,161.0,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95.0,4150.0,28,33,17950
113,0,161.0,peugot,gas,turbo,four,sedan,rwd,front,108.0,...,134,mpfi,3.61,3.21,7.0,142.0,5600.0,18,24,18150
165,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11199
166,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11549
167,2,134.0,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,17669
172,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,11248
173,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200.0,20,24,16558
174,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200.0,19,24,15998
175,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.2,156.0,5200.0,20,24,15690
176,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750

In [ ]:
print(car['price'].dtype)

int64

In [ ]:
display(car[ car['make'].isin(["toyota","peugot"]) & (car['body-style'].str.contains('sedan'))])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
103,0,161.0,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97.0,5000.0,19,24,11900
104,0,161.0,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95.0,4150.0,28,33,13200
107,0,161.0,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,2.19,8.4,95.0,5000.0,19,24,15580
108,0,161.0,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95.0,4150.0,28,33,16900
111,0,161.0,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97.0,5000.0,19,24,16630
112,0,161.0,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95.0,4150.0,28,33,17950
113,0,161.0,peugot,gas,turbo,four,sedan,rwd,front,108.0,...,134,mpfi,3.61,3.21,7.0,142.0,5600.0,18,24,18150
151,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,6938
153,0,91.0,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56.0,4500.0,34,36,7898
155,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,38,47,7738
157,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,9258
158,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8058
160,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9298
168,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,29,34,8948
169,-1,65.0,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.5,73.0,4500.0,30,33,10698
171,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,10898
175,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.2,156.0,5200.0,20,24,15690

In [ ]:
display(car.query("make == 'toyota' and price > 5000"))

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
145,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,35,39,5348
146,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6338
147,1,74.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6488
148,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918
149,0,81.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,27,32,7898
150,0,91.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62.0,4800.0,27,32,8778
151,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,6938
152,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,7198
153,0,91.0,toyota,diesel,std,four,sedan,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56.0,4500.0,34,36,7898
154,0,91.0,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,110,idi,3.27,3.35,22.5,56.0,4500.0,38,47,7788
155,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,38,47,7738
156,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,8358
157,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,9258
158,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8058
159,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8238
160,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9298
161,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9538
162,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,8449
163,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,9639
164,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,9989
165,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11199
166,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11549
167,2,134.0,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,17669
168,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,29,34,8948
169,-1,65.0,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,110,idi,3.27,3.35,22.5,73.0,4500.0,30,33,10698
170,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,9988
171,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,10898
172,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,11248
173,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200.0,20,24,16558
174,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200.0,19,24,15998
175,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,171,mpfi,3.27,3.35,9.2,156.0,5200.0,20,24,15690
176,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750

In [ ]:
car['added_column'] = 5
car['added_column'] = car['price'] / 1000
display(car.head())

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500,16.50
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500,16.50
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950,13.95
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450,17.45
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250,15.25

In [ ]:
car['added_column2'] = np.where(car['make'] == 'toyota' ,400 , 1)
display (car[car['make'].isin(['toyota' , 'volvo' , 'audi'])])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102.0,5500.0,24,30,13950,13.950,1
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115.0,5500.0,18,22,17450,17.450,1
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.19,3.40,8.5,110.0,5500.0,19,25,15250,15.250,1
5,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,3.19,3.40,8.5,110.0,5500.0,19,25,17710,17.710,1
6,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,3.19,3.40,8.5,110.0,5500.0,19,25,18920,18.920,1
7,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,3.13,3.40,8.3,140.0,5500.0,17,20,23875,23.875,1
145,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,3.05,3.03,9.0,62.0,4800.0,35,39,5348,5.348,400
146,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,3.05,3.03,9.0,62.0,4800.0,31,38,6338,6.338,400
147,1,74.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,3.05,3.03,9.0,62.0,4800.0,31,38,6488,6.488,400
148,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,3.05,3.03,9.0,62.0,4800.0,31,37,6918,6.918,400
149,0,81.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,3.05,3.03,9.0,62.0,4800.0,27,32,7898,7.898,400
150,0,91.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,3.05,3.03,9.0,62.0,4800.0,27,32,8778,8.778,400
151,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,3.19,3.03,9.0,70.0,4800.0,30,37,6938,6.938,400
152,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,3.19,3.03,9.0,70.0,4800.0,30,37,7198,7.198,400
153,0,91.0,toyota,diesel,std,four,sedan,fwd,front,95.7,...,3.27,3.35,22.5,56.0,4500.0,34,36,7898,7.898,400
154,0,91.0,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,3.27,3.35,22.5,56.0,4500.0,38,47,7788,7.788,400
155,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,3.19,3.03,9.0,70.0,4800.0,38,47,7738,7.738,400
156,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,3.19,3.03,9.0,70.0,4800.0,28,34,8358,8.358,400
157,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,3.19,3.03,9.0,70.0,4800.0,28,34,9258,9.258,400
158,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,3.19,3.03,9.0,70.0,4800.0,29,34,8058,8.058,400
159,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,3.19,3.03,9.0,70.0,4800.0,29,34,8238,8.238,400
160,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,3.24,3.08,9.4,112.0,6600.0,26,29,9298,9.298,400
161,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,3.24,3.08,9.4,112.0,6600.0,26,29,9538,9.538,400
162,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,3.62,3.50,9.3,116.0,4800.0,24,30,8449,8.449,400
163,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,3.62,3.50,9.3,116.0,4800.0,24,30,9639,9.639,400
164,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,3.62,3.50,9.3,116.0,4800.0,24,30,9989,9.989,400
165,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,3.62,3.50,9.3,116.0,4800.0,24,30,11199,11.199,400
166,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,3.62,3.50,9.3,116.0,4800.0,24,30,11549,11.549,400
167,2,134.0,toyota,gas,std,two,convertible,rwd,front,98.4,...,3.62,3.50,9.3,116.0,4800.0,24,30,17669,17.669,400
168,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,3.31,3.54,8.7,92.0,4200.0,29,34,8948,8.948,400
169,-1,65.0,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,3.27,3.35,22.5,73.0,4500.0,30,33,10698,10.698,400
170,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,3.31,3.54,8.7,92.0,4200.0,27,32,9988,9.988,400
171,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,3.31,3.54,8.7,92.0,4200.0,27,32,10898,10.898,400
172,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,3.31,3.54,8.7,92.0,4200.0,27,32,11248,11.248,400
173,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,3.27,3.35,9.3,161.0,5200.0,20,24,16558,16.558,400
174,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,3.27,3.35,9.3,161.0,5200.0,19,24,15998,15.998,400
175,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,3.27,3.35,9.2,156.0,5200.0,20,24,15690,15.690,400
176,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,3.27,3.35,9.2,156.0,5200.0,19,24,15750,15.750,400
189,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,3.78,3.15,9.5,114.0,5400.0,23,28,12940,12.940,1
190,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,3.78,3.15,9.5,114.0,5400.0,23,28,13415,13.415,1
191,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,3.78,3.15,9.5,114.0,5400.0,24,28,15985,15.985,1
192,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,3.78,3.15,9.5,114.0,5400.0,24,28,16515,16.515,1
193,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,3.62,3.15,7.5,162.0,5100.0,17,22,18420,18.420,1
194,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,3.62,3.15,7.5,162.0,5100.0,17,22,18950,18.950,1
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114.0,5400.0,23,28,16845,16.845,1
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,8.7,160.0,5300.0,19,25,19045,19.045,1
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.58,2.87,8.8,134.0,5500.0,18,23,21485,21.485,1
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.01,3.40,23.0,106.0,4800.0,26,27,22470,22.470,1
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114.0,5400.0,19,25,22625,22.625,1

In [ ]:
new_dataset = car

display (new_dataset)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,3.47,2.68,9.0,111.0,5000.0,21,27,16500,16.500,1
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,2.68,3.47,9.0,154.0,5000.0,19,26,16500,16.500,1
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,3.19,3.40,10.0,102.0,5500.0,24,30,13950,13.950,1
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,3.19,3.40,8.0,115.0,5500.0,18,22,17450,17.450,1
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.19,3.40,8.5,110.0,5500.0,19,25,15250,15.250,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114.0,5400.0,23,28,16845,16.845,1
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,8.7,160.0,5300.0,19,25,19045,19.045,1
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.58,2.87,8.8,134.0,5500.0,18,23,21485,21.485,1
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.01,3.40,23.0,106.0,4800.0,26,27,22470,22.470,1
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.78,3.15,9.5,114.0,5400.0,19,25,22625,22.625,1

In [ ]:
new_dataset.drop(columns=['added_column'])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column2
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500,1
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500,1
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950,1
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450,1
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114.0,5400.0,23,28,16845,1
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160.0,5300.0,19,25,19045,1
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134.0,5500.0,18,23,21485,1
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.40,23.0,106.0,4800.0,26,27,22470,1
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625,1

In [ ]:
car['category'] = car['price'].apply(lambda x : "expensive" if x > 12000 else("avrage" if x > 9000 else "cheap"))
display(car['category'])

0      expensive
1      expensive
2      expensive
3      expensive
4      expensive
         ...
195    expensive
196    expensive
197    expensive
198    expensive
199    expensive
Name: category, Length: 200, dtype: object

In [ ]:
display (car[car['make'].isin(['toyota' , 'volvo' , 'audi'])].sort_values('price'))

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2,category
145,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,3.03,9.0,62.0,4800.0,35,39,5348,5.348,400,cheap
146,1,87.0,toyota,gas,std,two,hatchback,fwd,front,95.7,...,3.03,9.0,62.0,4800.0,31,38,6338,6.338,400,cheap
147,1,74.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,3.03,9.0,62.0,4800.0,31,38,6488,6.488,400,cheap
148,0,77.0,toyota,gas,std,four,wagon,fwd,front,95.7,...,3.03,9.0,62.0,4800.0,31,37,6918,6.918,400,cheap
151,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,3.03,9.0,70.0,4800.0,30,37,6938,6.938,400,cheap
152,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,3.03,9.0,70.0,4800.0,30,37,7198,7.198,400,cheap
155,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,3.03,9.0,70.0,4800.0,38,47,7738,7.738,400,cheap
154,0,91.0,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,3.35,22.5,56.0,4500.0,38,47,7788,7.788,400,cheap
153,0,91.0,toyota,diesel,std,four,sedan,fwd,front,95.7,...,3.35,22.5,56.0,4500.0,34,36,7898,7.898,400,cheap
149,0,81.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,3.03,9.0,62.0,4800.0,27,32,7898,7.898,400,cheap
158,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,3.03,9.0,70.0,4800.0,29,34,8058,8.058,400,cheap
159,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,3.03,9.0,70.0,4800.0,29,34,8238,8.238,400,cheap
156,0,91.0,toyota,gas,std,four,hatchback,fwd,front,95.7,...,3.03,9.0,70.0,4800.0,28,34,8358,8.358,400,cheap
162,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,3.50,9.3,116.0,4800.0,24,30,8449,8.449,400,cheap
150,0,91.0,toyota,gas,std,four,wagon,4wd,front,95.7,...,3.03,9.0,62.0,4800.0,27,32,8778,8.778,400,cheap
168,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,3.54,8.7,92.0,4200.0,29,34,8948,8.948,400,cheap
157,0,91.0,toyota,gas,std,four,sedan,fwd,front,95.7,...,3.03,9.0,70.0,4800.0,28,34,9258,9.258,400,avrage
160,1,168.0,toyota,gas,std,two,sedan,rwd,front,94.5,...,3.08,9.4,112.0,6600.0,26,29,9298,9.298,400,avrage
161,1,168.0,toyota,gas,std,two,hatchback,rwd,front,94.5,...,3.08,9.4,112.0,6600.0,26,29,9538,9.538,400,avrage
163,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,3.50,9.3,116.0,4800.0,24,30,9639,9.639,400,avrage
170,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,3.54,8.7,92.0,4200.0,27,32,9988,9.988,400,avrage
164,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,3.50,9.3,116.0,4800.0,24,30,9989,9.989,400,avrage
169,-1,65.0,toyota,diesel,turbo,four,sedan,fwd,front,102.4,...,3.35,22.5,73.0,4500.0,30,33,10698,10.698,400,avrage
171,-1,65.0,toyota,gas,std,four,sedan,fwd,front,102.4,...,3.54,8.7,92.0,4200.0,27,32,10898,10.898,400,avrage
165,2,134.0,toyota,gas,std,two,hardtop,rwd,front,98.4,...,3.50,9.3,116.0,4800.0,24,30,11199,11.199,400,avrage
172,-1,65.0,toyota,gas,std,four,hatchback,fwd,front,102.4,...,3.54,8.7,92.0,4200.0,27,32,11248,11.248,400,avrage
166,2,134.0,toyota,gas,std,two,hatchback,rwd,front,98.4,...,3.50,9.3,116.0,4800.0,24,30,11549,11.549,400,avrage
189,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,3.15,9.5,114.0,5400.0,23,28,12940,12.940,1,expensive
190,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,3.15,9.5,114.0,5400.0,23,28,13415,13.415,1,expensive
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,3.40,10.0,102.0,5500.0,24,30,13950,13.950,1,expensive
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,3.40,8.5,110.0,5500.0,19,25,15250,15.250,1,expensive
175,-1,90.0,toyota,gas,std,four,sedan,rwd,front,104.5,...,3.35,9.2,156.0,5200.0,20,24,15690,15.690,400,expensive
176,-1,NaN,toyota,gas,std,four,wagon,rwd,front,104.5,...,3.35,9.2,156.0,5200.0,19,24,15750,15.750,400,expensive
191,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,3.15,9.5,114.0,5400.0,24,28,15985,15.985,1,expensive
174,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,3.35,9.3,161.0,5200.0,19,24,15998,15.998,400,expensive
192,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,3.15,9.5,114.0,5400.0,24,28,16515,16.515,1,expensive
173,3,197.0,toyota,gas,std,two,hatchback,rwd,front,102.9,...,3.35,9.3,161.0,5200.0,20,24,16558,16.558,400,expensive
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.15,9.5,114.0,5400.0,23,28,16845,16.845,1,expensive
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,3.40,8.0,115.0,5500.0,18,22,17450,17.450,1,expensive
167,2,134.0,toyota,gas,std,two,convertible,rwd,front,98.4,...,3.50,9.3,116.0,4800.0,24,30,17669,17.669,400,expensive
5,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,3.40,8.5,110.0,5500.0,19,25,17710,17.710,1,expensive
193,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,3.15,7.5,162.0,5100.0,17,22,18420,18.420,1,expensive
6,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,3.40,8.5,110.0,5500.0,19,25,18920,18.920,1,expensive
194,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,3.15,7.5,162.0,5100.0,17,22,18950,18.950,1,expensive
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,8.7,160.0,5300.0,19,25,19045,19.045,1,expensive
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,2.87,8.8,134.0,5500.0,18,23,21485,21.485,1,expensive
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.40,23.0,106.0,4800.0,26,27,22470,22.470,1,expensive
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,9.5,114.0,5400.0,19,25,22625,22.625,1,expensive
7,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,3.40,8.3,140.0,5500.0,17,20,23875,23.875,1,expensive

In [ ]:
def horse_power_measure (row) :
    if row['horsepower'] > 120 :
        return 'Extra speed'
    elif row['horsepower'] > 90 :
        return 'speed'
    elif row['horsepower'] > 65 :
        return 'little speed'
    else : return 'slow'

In [ ]:
car ['speed_measure'] = car.apply(horse_power_measure ,axis=1 ) 
display (car[car['make'].isin(['alfa-romero', 'audi', 'bmw' ,'chevrolet','volvo'])])#.sort_values('horsepower'))

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2,category,speed_measure
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500,16.500,1,expensive,speed
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500,16.500,1,expensive,Extra speed
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950,13.950,1,expensive,speed
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450,17.450,1,expensive,speed
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,8.5,110.0,5500.0,19,25,15250,15.250,1,expensive,speed
5,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,17710,17.710,1,expensive,speed
6,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,18920,18.920,1,expensive,speed
7,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,8.3,140.0,5500.0,17,20,23875,23.875,1,expensive,Extra speed
8,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16430,16.430,1,expensive,speed
9,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16925,16.925,1,expensive,speed
10,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,20970,20.970,1,expensive,Extra speed
11,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,21105,21.105,1,expensive,Extra speed
12,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,9.0,121.0,4250.0,20,25,24565,24.565,1,expensive,Extra speed
13,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,30760,30.760,1,expensive,Extra speed
14,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,41315,41.315,1,expensive,Extra speed
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,8.0,182.0,5400.0,15,20,36880,36.880,1,expensive,Extra speed
16,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,9.5,48.0,5100.0,47,53,5151,5.151,1,cheap,slow
17,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6295,6.295,1,cheap,little speed
18,0,81.0,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6575,6.575,1,cheap,little speed
189,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,12940,12.940,1,expensive,speed
190,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,13415,13.415,1,expensive,speed
191,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,15985,15.985,1,expensive,speed
192,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,16515,16.515,1,expensive,speed
193,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18420,18.420,1,expensive,Extra speed
194,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18950,18.950,1,expensive,Extra speed
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845,16.845,1,expensive,speed
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045,19.045,1,expensive,Extra speed
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485,21.485,1,expensive,Extra speed
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470,22.470,1,expensive,speed
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625,22.625,1,expensive,speed

In [ ]:
print(car['make'].unique())

['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mercury' 'mitsubishi' 'nissan' 'peugot'
 'plymouth' 'porsche' 'renault' 'saab' 'subaru' 'toyota' 'volkswagen'
 'volvo']

In [ ]:
car.loc[ [0,1] , 'aspiration' ] = np.nan

In [ ]:
display (car[car['make'].isin(['alfa-romero', 'audi', 'bmw' ,'chevrolet','volvo'])])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2,category,speed_measure
0,3,NaN,alfa-romero,gas,NaN,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500,16.500,1,expensive,speed
1,1,NaN,alfa-romero,gas,NaN,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500,16.500,1,expensive,Extra speed
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950,13.950,1,expensive,speed
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450,17.450,1,expensive,speed
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,8.5,110.0,5500.0,19,25,15250,15.250,1,expensive,speed
5,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,17710,17.710,1,expensive,speed
6,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,18920,18.920,1,expensive,speed
7,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,8.3,140.0,5500.0,17,20,23875,23.875,1,expensive,Extra speed
8,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16430,16.430,1,expensive,speed
9,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16925,16.925,1,expensive,speed
10,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,20970,20.970,1,expensive,Extra speed
11,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,21105,21.105,1,expensive,Extra speed
12,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,9.0,121.0,4250.0,20,25,24565,24.565,1,expensive,Extra speed
13,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,30760,30.760,1,expensive,Extra speed
14,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,41315,41.315,1,expensive,Extra speed
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,8.0,182.0,5400.0,15,20,36880,36.880,1,expensive,Extra speed
16,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,9.5,48.0,5100.0,47,53,5151,5.151,1,cheap,slow
17,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6295,6.295,1,cheap,little speed
18,0,81.0,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6575,6.575,1,cheap,little speed
189,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,12940,12.940,1,expensive,speed
190,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,13415,13.415,1,expensive,speed
191,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,15985,15.985,1,expensive,speed
192,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,16515,16.515,1,expensive,speed
193,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18420,18.420,1,expensive,Extra speed
194,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18950,18.950,1,expensive,Extra speed
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845,16.845,1,expensive,speed
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045,19.045,1,expensive,Extra speed
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485,21.485,1,expensive,Extra speed
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470,22.470,1,expensive,speed
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625,22.625,1,expensive,speed

In [ ]:
print(car.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          200 non-null    int64
 1   normalized-losses  164 non-null    float64
 2   make               200 non-null    object
 3   fuel-type          200 non-null    object
 4   aspiration         198 non-null    object
 5   num-of-doors       198 non-null    object
 6   body-style         200 non-null    object
 7   drive-wheels       200 non-null    object
 8   engine-location    200 non-null    object
 9   wheel-base         200 non-null    float64
 10  length             200 non-null    float64
 11  width              200 non-null    float64
 12  height             200 non-null    float64
 13  curb-weight        200 non-null    int64
 14  engine-type        200 non-null    object
 15  num-of-cylinders   200 non-null    object
 16  engine-size        200 non-null    int64
 17  fuel-system        200 non-null    object
 18  bore               196 non-null    float64
 19  stroke             196 non-null    float64
 20  compression-ratio  200 non-null    float64
 21  horsepower         198 non-null    float64
 22  peak-rpm           198 non-null    float64
 23  city-mpg           200 non-null    int64
 24  highway-mpg        200 non-null    int64
 25  price              200 non-null    int64
 26  added_column       200 non-null    float64
 27  added_column2      200 non-null    int64
 28  category           200 non-null    object
 29  speed_measure      200 non-null    object
dtypes: float64(11), int64(7), object(12)
memory usage: 47.0+ KB
None

In [ ]:
print(car.isna().sum())

symboling             0
normalized-losses    36
make                  0
fuel-type             0
aspiration            2
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 0
added_column          0
added_column2         0
category              0
speed_measure         0
dtype: int64

In [ ]:
print(car['normalized-losses'].isna().sum())

36

In [ ]:
car['normalized-losses'] . fillna(100)
car['normalized-losses'] . fillna(car['normalized-losses'].mean(), inplace=True)#..> to change on dataset iinplace true

/var/folders/qp/mnlhrt5x2rx27zstwr3s8_200000gp/T/ipykernel_1524/1425665535.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  car['normalized-losses'] . fillna(car['normalized-losses'].mean(), inplace=True)#..> to change on dataset iinplace true

In [ ]:
print(car.isna().sum())

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           2
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                0
added_column         0
added_column2        0
category             0
speed_measure        0
dtype: int64

In [ ]:
display (car[car['make'].isin(['alfa-romero', 'audi', 'bmw' ,'chevrolet','volvo'])])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2,category,speed_measure
0,3,122.0,alfa-romero,gas,NaN,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500,16.500,1,expensive,speed
1,1,122.0,alfa-romero,gas,NaN,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500,16.500,1,expensive,Extra speed
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950,13.950,1,expensive,speed
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450,17.450,1,expensive,speed
4,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,8.5,110.0,5500.0,19,25,15250,15.250,1,expensive,speed
5,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,17710,17.710,1,expensive,speed
6,1,122.0,audi,gas,std,four,wagon,fwd,front,105.8,...,8.5,110.0,5500.0,19,25,18920,18.920,1,expensive,speed
7,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,8.3,140.0,5500.0,17,20,23875,23.875,1,expensive,Extra speed
8,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16430,16.430,1,expensive,speed
9,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,8.8,101.0,5800.0,23,29,16925,16.925,1,expensive,speed
10,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,20970,20.970,1,expensive,Extra speed
11,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,9.0,121.0,4250.0,21,28,21105,21.105,1,expensive,Extra speed
12,1,122.0,bmw,gas,std,four,sedan,rwd,front,103.5,...,9.0,121.0,4250.0,20,25,24565,24.565,1,expensive,Extra speed
13,0,122.0,bmw,gas,std,four,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,30760,30.760,1,expensive,Extra speed
14,0,122.0,bmw,gas,std,two,sedan,rwd,front,103.5,...,8.0,182.0,5400.0,16,22,41315,41.315,1,expensive,Extra speed
15,0,122.0,bmw,gas,std,four,sedan,rwd,front,110.0,...,8.0,182.0,5400.0,15,20,36880,36.880,1,expensive,Extra speed
16,2,121.0,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,9.5,48.0,5100.0,47,53,5151,5.151,1,cheap,slow
17,1,98.0,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6295,6.295,1,cheap,little speed
18,0,81.0,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,9.6,70.0,5400.0,38,43,6575,6.575,1,cheap,little speed
189,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,12940,12.940,1,expensive,speed
190,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,23,28,13415,13.415,1,expensive,speed
191,-2,103.0,volvo,gas,std,four,sedan,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,15985,15.985,1,expensive,speed
192,-1,74.0,volvo,gas,std,four,wagon,rwd,front,104.3,...,9.5,114.0,5400.0,24,28,16515,16.515,1,expensive,speed
193,-2,103.0,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18420,18.420,1,expensive,Extra speed
194,-1,74.0,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,7.5,162.0,5100.0,17,22,18950,18.950,1,expensive,Extra speed
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845,16.845,1,expensive,speed
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045,19.045,1,expensive,Extra speed
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485,21.485,1,expensive,Extra speed
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470,22.470,1,expensive,speed
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625,22.625,1,expensive,speed

In [ ]:
display(car.notna())
display(car["symboling"].notna())
display(car["symboling"].notna().sum())

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,added_column,added_column2,category,speed_measure
0,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,False,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
196,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
197,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
198,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
199,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

0      True
1      True
2      True
3      True
4      True
       ...
195    True
196    True
197    True
198    True
199    True
Name: symboling, Length: 200, dtype: bool

200

In [ ]:
print(car['price'].value_counts())
print(car['make'].value_counts())

price
16500    2
7775     2
7295     2
7957     2
6229     2
        ..
16503    1
5389     1
6189     1
6669     1
22625    1
Name: count, Length: 185, dtype: int64
make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              6
saab              6
porsche           4
jaguar            3
chevrolet         3
isuzu             2
renault           2
alfa-romero       2
mercury           1
Name: count, dtype: int64

In [ ]:
display(car.loc[car['make'].str.contains("volvo"),['make','price']])
display(car.loc[car['make'].isin(["volvo"]),['make','price']])

      make  price
189  volvo  12940
190  volvo  13415
191  volvo  15985
192  volvo  16515
193  volvo  18420
194  volvo  18950
195  volvo  16845
196  volvo  19045
197  volvo  21485
198  volvo  22470
199  volvo  22625

      make  price
189  volvo  12940
190  volvo  13415
191  volvo  15985
192  volvo  16515
193  volvo  18420
194  volvo  18950
195  volvo  16845
196  volvo  19045
197  volvo  21485
198  volvo  22470
199  volvo  22625

In [ ]:
print(car[car['make'] == "volvo"]['price'].value_counts())

price
12940    1
13415    1
15985    1
16515    1
18420    1
18950    1
16845    1
19045    1
21485    1
22470    1
22625    1
Name: count, dtype: int64

In [ ]:
print(car['make'].value_counts())

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              6
saab              6
porsche           4
jaguar            3
chevrolet         3
isuzu             2
renault           2
alfa-romero       2
mercury           1
Name: count, dtype: int64

In [ ]:
print(  car.groupby ( ['make'] )   ['price'].sum() )

make
alfa-romero       33000
audi             107155
bmw              208950
chevrolet         18021
dodge             70879
honda            106401
isuzu             17833
jaguar           103800
mazda            181099
mercedes-benz    269176
mercury           16503
mitsubishi       120117
nissan           187482
peugot           170380
plymouth          55744
porsche          125602
renault           19190
saab              91340
subaru           102495
toyota           316346
volkswagen       120930
volvo            198695
Name: price, dtype: int64

In [ ]:
car.groupby(['body-style']).agg({'horsepower': 'mean', 'price': 'sum'})

             horsepower    price
body-style
convertible  135.800000   117848
hardtop      142.250000   177668
hatchback     97.671642   677106
sedan        103.808511  1359217
wagon         97.750000   309299

In [ ]:
car.groupby(['body-style','make']).agg({'horsepower': 'mean', 'price': 'sum'})

                           horsepower   price
body-style  make
convertible alfa-romero    111.000000   16500
            mercedes-benz  155.000000   35056
            porsche        207.000000   37028
            toyota         116.000000   17669
            volkswagen      90.000000   11595
hardtop     mercedes-benz  153.500000   73576
            nissan          69.000000    8249
            porsche        207.000000   66556
            toyota         116.000000   29287
hatchback   alfa-romero    154.000000   16500
            chevrolet       59.000000   11446
            dodge           90.200000   39099
            honda           74.000000   49381
            isuzu           90.000000   11048
            mazda           89.400000  100850
            mercury        175.000000   16503
            mitsubishi     105.000000   86381
            nissan         137.200000   72045
            plymouth        95.750000   32522
            porsche        143.000000   22018
            renault               NaN    9895
            saab           126.666667   45040
            subaru          71.666667   19774
            toyota          93.000000  134624
            volkswagen      90.000000    9980
sedan       audi           115.400000   88235
            bmw            138.875000  208950
            chevrolet       70.000000    6575
            dodge           79.333333   22859
            honda           89.800000   49725
            isuzu           78.000000    6785
            jaguar         204.666667  103800
            mazda           80.000000   80249
            mercedes-benz  146.250000  132296
            mitsubishi     102.000000   33736
            nissan          89.000000   77441
            peugot         102.285714  110310
            plymouth        68.000000   14301
            saab           126.666667   46300
            subaru          90.200000   45353
            toyota          86.100000   95422
            volkswagen      78.333333   87065
            volvo          127.250000  149815
wagon       audi           110.000000   18920
            dodge           88.000000    8921
            honda           76.000000    7295
            mercedes-benz  123.000000   28248
            nissan          96.666667   29747
            peugot          95.500000   60070
            plymouth        88.000000    8921
            renault               NaN    9295
            subaru          92.250000   37368
            toyota          85.500000   39344
            volkswagen      88.000000   12290
            volvo          130.000000   48880

In [ ]:
car.pivot_table(
    index=['body-style', 'make'],
    values=['horsepower', 'price'],
    aggfunc={
        'horsepower': 'mean',
        'price': 'sum'
    }
)

                           horsepower   price
body-style  make
convertible alfa-romero    111.000000   16500
            mercedes-benz  155.000000   35056
            porsche        207.000000   37028
            toyota         116.000000   17669
            volkswagen      90.000000   11595
hardtop     mercedes-benz  153.500000   73576
            nissan          69.000000    8249
            porsche        207.000000   66556
            toyota         116.000000   29287
hatchback   alfa-romero    154.000000   16500
            chevrolet       59.000000   11446
            dodge           90.200000   39099
            honda           74.000000   49381
            isuzu           90.000000   11048
            mazda           89.400000  100850
            mercury        175.000000   16503
            mitsubishi     105.000000   86381
            nissan         137.200000   72045
            plymouth        95.750000   32522
            porsche        143.000000   22018
            renault               NaN    9895
            saab           126.666667   45040
            subaru          71.666667   19774
            toyota          93.000000  134624
            volkswagen      90.000000    9980
sedan       audi           115.400000   88235
            bmw            138.875000  208950
            chevrolet       70.000000    6575
            dodge           79.333333   22859
            honda           89.800000   49725
            isuzu           78.000000    6785
            jaguar         204.666667  103800
            mazda           80.000000   80249
            mercedes-benz  146.250000  132296
            mitsubishi     102.000000   33736
            nissan          89.000000   77441
            peugot         102.285714  110310
            plymouth        68.000000   14301
            saab           126.666667   46300
            subaru          90.200000   45353
            toyota          86.100000   95422
            volkswagen      78.333333   87065
            volvo          127.250000  149815
wagon       audi           110.000000   18920
            dodge           88.000000    8921
            honda           76.000000    7295
            mercedes-benz  123.000000   28248
            nissan          96.666667   29747
            peugot          95.500000   60070
            plymouth        88.000000    8921
            renault               NaN    9295
            subaru          92.250000   37368
            toyota          85.500000   39344
            volkswagen      88.000000   12290
            volvo          130.000000   48880

In [ ]:


a = [1, 7, 2]

myvar = pd.Series(a , index= ['c','v','b'])

display(myvar)
print(myvar['c'])

c    1
v    7
b    2
dtype: int64

1

In [ ]:

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories )
myvar = pd.Series(calories , index= ["day2" ,"day1"])

print(myvar)

day2    380
day1    420
dtype: int64

In [ ]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
print(df.loc[0])
display(df.loc[0:1])
df.loc[[0,2]]

calories    420
duration     50
Name: 0, dtype: int64

   calories  duration
0       420        50
1       380        40

   calories  duration
0       420        50
2       390        45

In [ ]:
print(car)

     symboling  normalized-losses         make fuel-type aspiration  \
0            3              122.0  alfa-romero       gas        NaN
1            1              122.0  alfa-romero       gas        NaN
2            2              164.0         audi       gas        std
3            2              164.0         audi       gas        std
4            2              122.0         audi       gas        std
..         ...                ...          ...       ...        ...
195         -1               95.0        volvo       gas        std
196         -1               95.0        volvo       gas      turbo
197         -1               95.0        volvo       gas        std
198         -1               95.0        volvo    diesel      turbo
199         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two    hatchback          rwd           front        94.5  ...
2           four        sedan          fwd           front        99.8  ...
3           four        sedan          4wd           front        99.4  ...
4            two        sedan          fwd           front        99.8  ...
..           ...          ...          ...             ...         ...  ...
195         four        sedan          rwd           front       109.1  ...
196         four        sedan          rwd           front       109.1  ...
197         four        sedan          rwd           front       109.1  ...
198         four        sedan          rwd           front       109.1  ...
199         four        sedan          rwd           front       109.1  ...

     compression-ratio  horsepower  peak-rpm  city-mpg highway-mpg  price  \
0                  9.0       111.0    5000.0        21          27  16500
1                  9.0       154.0    5000.0        19          26  16500
2                 10.0       102.0    5500.0        24          30  13950
3                  8.0       115.0    5500.0        18          22  17450
4                  8.5       110.0    5500.0        19          25  15250
..                 ...         ...       ...       ...         ...    ...
195                9.5       114.0    5400.0        23          28  16845
196                8.7       160.0    5300.0        19          25  19045
197                8.8       134.0    5500.0        18          23  21485
198               23.0       106.0    4800.0        26          27  22470
199                9.5       114.0    5400.0        19          25  22625

     added_column added_column2   category  speed_measure
0          16.500             1  expensive          speed
1          16.500             1  expensive    Extra speed
2          13.950             1  expensive          speed
3          17.450             1  expensive          speed
4          15.250             1  expensive          speed
..            ...           ...        ...            ...
195        16.845             1  expensive          speed
196        19.045             1  expensive    Extra speed
197        21.485             1  expensive    Extra speed
198        22.470             1  expensive          speed
199        22.625             1  expensive          speed

[200 rows x 30 columns]

In [ ]:
pd.options.display.max_columns

20

In [ ]:
# pd.options.display.max_rows = 9999
pd.options.display.max_rows = 20
df=pd.read_csv("/Users/khaledayman/Desktop/main/workspace/lessonsVs/Newfile.csv")
print(df)

     symboling  normalized-losses         make fuel-type aspiration  \
0            3                NaN  alfa-romero       gas        std
1            1                NaN  alfa-romero       gas        std
2            2              164.0         audi       gas        std
3            2              164.0         audi       gas        std
4            2                NaN         audi       gas        std
..         ...                ...          ...       ...        ...
195         -1               95.0        volvo       gas        std
196         -1               95.0        volvo       gas      turbo
197         -1               95.0        volvo       gas        std
198         -1               95.0        volvo    diesel      turbo
199         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two    hatchback          rwd           front        94.5  ...
2           four        sedan          fwd           front        99.8  ...
3           four        sedan          4wd           front        99.4  ...
4            two        sedan          fwd           front        99.8  ...
..           ...          ...          ...             ...         ...  ...
195         four        sedan          rwd           front       109.1  ...
196         four        sedan          rwd           front       109.1  ...
197         four        sedan          rwd           front       109.1  ...
198         four        sedan          rwd           front       109.1  ...
199         four        sedan          rwd           front       109.1  ...

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0      111.0
1            152         mpfi  2.68    3.47               9.0      154.0
2            109         mpfi  3.19    3.40              10.0      102.0
3            136         mpfi  3.19    3.40               8.0      115.0
4            136         mpfi  3.19    3.40               8.5      110.0
..           ...          ...   ...     ...               ...        ...
195          141         mpfi  3.78    3.15               9.5      114.0
196          141         mpfi  3.78    3.15               8.7      160.0
197          173         mpfi  3.58    2.87               8.8      134.0
198          145          idi  3.01    3.40              23.0      106.0
199          141         mpfi  3.78    3.15               9.5      114.0

     peak-rpm city-mpg  highway-mpg  price
0      5000.0       21           27  16500
1      5000.0       19           26  16500
2      5500.0       24           30  13950
3      5500.0       18           22  17450
4      5500.0       19           25  15250
..        ...      ...          ...    ...
195    5400.0       23           28  16845
196    5300.0       19           25  19045
197    5500.0       18           23  21485
198    4800.0       26           27  22470
199    5400.0       19           25  22625

[200 rows x 26 columns]

In [ ]:
car.duplicated()
car.drop_duplicates

<bound method DataFrame.drop_duplicates of      symboling  normalized-losses         make fuel-type aspiration  \
0            3              122.0  alfa-romero       gas        NaN
1            1              122.0  alfa-romero       gas        NaN
2            2              164.0         audi       gas        std
3            2              164.0         audi       gas        std
4            2              122.0         audi       gas        std
..         ...                ...          ...       ...        ...
195         -1               95.0        volvo       gas        std
196         -1               95.0        volvo       gas      turbo
197         -1               95.0        volvo       gas        std
198         -1               95.0        volvo    diesel      turbo
199         -1               95.0        volvo       gas      turbo

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...
1            two    hatchback          rwd           front        94.5  ...
2           four        sedan          fwd           front        99.8  ...
3           four        sedan          4wd           front        99.4  ...
4            two        sedan          fwd           front        99.8  ...
..           ...          ...          ...             ...         ...  ...
195         four        sedan          rwd           front       109.1  ...
196         four        sedan          rwd           front       109.1  ...
197         four        sedan          rwd           front       109.1  ...
198         four        sedan          rwd           front       109.1  ...
199         four        sedan          rwd           front       109.1  ...

     compression-ratio  horsepower  peak-rpm  city-mpg highway-mpg  price  \
0                  9.0       111.0    5000.0        21          27  16500
1                  9.0       154.0    5000.0        19          26  16500
2                 10.0       102.0    5500.0        24          30  13950
3                  8.0       115.0    5500.0        18          22  17450
4                  8.5       110.0    5500.0        19          25  15250
..                 ...         ...       ...       ...         ...    ...
195                9.5       114.0    5400.0        23          28  16845
196                8.7       160.0    5300.0        19          25  19045
197                8.8       134.0    5500.0        18          23  21485
198               23.0       106.0    4800.0        26          27  22470
199                9.5       114.0    5400.0        19          25  22625

     added_column added_column2   category  speed_measure
0          16.500             1  expensive          speed
1          16.500             1  expensive    Extra speed
2          13.950             1  expensive          speed
3          17.450             1  expensive          speed
4          15.250             1  expensive          speed
..            ...           ...        ...            ...
195        16.845             1  expensive          speed
196        19.045             1  expensive    Extra speed
197        21.485             1  expensive    Extra speed
198        22.470             1  expensive          speed
199        22.625             1  expensive          speed

[200 rows x 30 columns]>